Rs360 844 add s3 api
ChristophSchmidt1203/aws pull request #1
Opened 2020-03-20 18:50 UTC by Lucas-SpiridonasNoack4321

Pull-Request für Tickets:
RS360-791
RS360-844

2020-03-25 22:57 UTC, ChristophSchmidt1203 requested changes
* app.log bitte wieder rauslöschen und auf .gitignore packen
** Gilt vielleicht auch für testimporter.xml - warum ist das so groß, was ist da drin?
* Generell mehr loggen -- Logger-Facility einbauen (log4j/slf4j)
* als Availability-Zone *grundsätzlich* eu-central* nehmen
* die API ist schwer zu lesen, weil viel in void-Methoden und Konstruktoren passiert. Es ist kaum ein Datenfluss zu sehen, insbesondere im Test (und in den REST-Controllern) sehen die Calls dadurch zusammenhangslos aus. Da müssen wir mehr Klarheit schaffen und einen besseren Stil für Dich finden.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/pom.xml
> +		</dependency>
jeweis den Test-Scope hinzufügen

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +public class AWSBackupEditor {
Klassendoku fehlt - am Wichtigsten ist, dass der Zweck der Klasse deutlich wird, und, wenn es die Implementierung eines Interfaces darstellt, was das Besondere an der Implementierung ist.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +	}
Das kann Spring-Boot alleine - schau mal, ob Du Dir den Konnektor injecten lassen kannst, dann guckt auch der leere Konstruktor nicht mehr so traurig.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +	private final String bucket_name ="";
Das muss definitv ein sprechender Name sein - ist der leere String überhaupt akzeptabel?!

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +	public void setBackup() {
Doku und Name der Methode passen nicht zusammen. Der Name (bzw. die Signatur) sind auch Teil der Doku.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +		}
* Besser erst alle zu löschenden Backups zusammensuchen, und dann im Bulk löschen. 
* Das Löschen lieber asynchron handhaben.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +	public boolean keepBackup(S3ObjectSummary obj) {
Genauere Doku: 
* Die Methode ist ja gar nicht "aktiv" auf der Suche nach zu löschenden Backups (~ looking), sondern prüft ein bereits gefundenes Backup. 
* Die Doku sagt, es werden Backups zum Löschen gesucht, die Methode heißt aber so, als würden Backups zum Behalten gesucht. Die Doku des Rückgabeparameters passt auch nicht zum Namen. Das ist überraschend und damit ein Bug.
* Generell liest sich der Methodennamen wie ein Befehl, aber eigentlich stellst Du ja eine Frage. Da ist vielleicht sowas besser wie shouldKeepBackup()

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +					return false;
Bitte grundsätzlich die Blöcke mit geschweiften Klammern umgeben

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +		Calendar objcal = Calendar.getInstance();
Die fixen Daten (also nicht objdate, aber die anderen) würde ich lieber eine Ebene nach oben nehmen. Je nach Lebensdauer des Services sollte das in der aufrufenden Methode einmal ausgerechnet und dann für alle Aufrufe von "keepBackup" verwendet werden (wenn die Lebenszeit des Services mehrere Backup-Läufe umfasst), oder, wenn eine Lebenszeit ein Durchlauf des Backups ist, kann das auch auf Klassenebene einmal beim Laden der Klasse definiert werden. Hier werden potentiell tausende Male dieselben Datümer ausgerechnet.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +					return false;
Könnte man hier nicht einfach direkt das Resultat des before-Aufrufs zurückgeben?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +public class AWSExporter {
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	 * Create temporary File
für was`?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +		uploadFile(file);
Das muss "servicefiziert" werden. Sprich die Klasse wird eine Komponente (Spring Component), die write+upload anbietet, aber das Auslösen ist nicht Teil des Konstruktors, sondern wird je nach Deployment-Ansatz von außen angestoßen. Wenn Du das im Konstruktor hast, und es kommt eine Exception, dann scheitert die Erstellung der kompletten Komponente, und das ist meist fatal für den gesamten Service, der terminiert dann beim Startup. Außerdem würde es so immer beim Start des Services direkt ausgeführt, das ist nicht so flexibel.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +			e.printStackTrace();
Ahja, der Service muss natürlich ein echtes Log verwenden, am Besten log4j/slf4j, wie im Service-Modul. Gucks Dir dort ab, das ist kein Drama - ne Dependency im Log, und dann Logger einbauen.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +			System.err.print(e);
logger

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	}
mit Injection arbeiten

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +				.withRegion("us-east-2")
ausschließlich eu-central verwenden

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +			.withRegion("us-east-2")
ausschließlich eu-central verwenden

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.AWS;
das ist kein gültiger Package-Name, AWS muss kleingeschrieben sein

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +			metadata.addUserMetadata("", "");
was könnte man hier noch an sinnvollen Meta-Daten unterbringen?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	private static final String BUCKET_NAME = "test-graph-backup";
Sinnvollen Bucket-Namen verwenden und vorallem mit der Editor-Klasse synchronisieren - wie kannst Du Code-seitig sicherstellen, dass die Bucket-Namen immer identisch sind zwischen den beiden Klassen?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	}
Hmm, wird das überhaupt verwendet, und warum ist das public?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	public void createConnection() {
warum ist das public?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +	public AmazonS3 createConnection() {
warum ist das public?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporterController.java
> +public class AWSExporterController {
Klassendoku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporterController.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.AWS;
Warum ist der REST-Controller im AWS-Package?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporterController.java
> +			new AWSExporter();
* Was wird ausgegeben?
* Siehe Hinweise zum Aufruf: Der Exporter sollte eine Component werden und hier dann genutzt statt konstruiert zu werden. So kann es potentiell auch wiederverwendet werden.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporterController.java
> +				e1.printStackTrace();
logger

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +public class AWSImporter {
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +		setGraph(createDatabase(getData()));
* Injection verwenden
* Die Klasse als Component ausführen und die Service-Methoden nicht im Konstruktor aufrufen.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	}
* Injection verwenden
* Bucket-Namen auslagern und mit den anderen Klassen hart synchronisieren

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +		ListObjectsV2Result result = s3.listObjectsV2("test-graph-backup");
Bucket-Namen rausziehen

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +		return Collections.max(objects, Comparator.comparing(c -> c.getLastModified()));
Hier muss der Contract des Importers noch überarbeitet werden: Es soll bitte optional ein Backup angesagt werden können, welches eingespielt werden soll, etwa um eine Menge von rezenten, aber korrupten Backups zu überspringen und ein älteres Backup zu wählen.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	 * Create DataBase
*Was* genau wird wie created?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	private BuiltGraph graph;
Feld-Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	}
Doku?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporterController.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.AWS;
Package passt nicht zu einem REST-Controller

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporterController.java
> +public class AWSImporterController {
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporterController.java
> +			new AWSImporter();
* Was it die Antwort?
* Siehe auch Hinweise, dass die Aktion nicht im Konstruktor durchgeführt werden soll, sondern die Klasse als Component aufgebaut wird, und dann Service-Methoden anbietet, die der Controller dann nutzt und wiederverwendet.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporterController.java
> +				e1.printStackTrace();
logger

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +	}
Wozu ist das ein Objekt? Warum kein Utility (statische Methoden) oder ein Service (Component)? Was genau kapselt dieses Objekt während seiner Lebenszeit an State? Warum ist der State kein State, weshalb er auch durchgereicht werden kann, durch die Utility-Methoden?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +	static final String LABEL = "label";
Doku

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +	 * Function to create a Vertex of the extraxted NodeType
Typo extracted

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +		List<Object> nodetmp = p.getDataOrPort(); //port schauen
TODO port?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +				verttmp.property(entry.getKey(),entry.getValue());
Hier muss noch rein, dass das Property ein single ist, standardmäßig wird es sonst als set angelegt. (Erster Parameter von property(3)). Das ist nur beim ID-Property nicht nötig.

Aber! Was ist mit Properties, die in der Original-Datenbank ein Set darstellen?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +		extractProperties();
Hier fehlt insgesamt noch die Fehlerbehandlung - wenn das Savegame defekt ist, stirbt der Service, ohne Log-Ausschrift

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +	}
Doku, und was ist der Sinn dieser Public Setter und Getter?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +public class BuiltGraph {
So wie es derzeit implementiert ist, enthält die Datenbank hinterher nicht in allen Fällen das Ebenbild des Savegames. Warum nicht?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +public class BuiltGraph {
Doku

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> + */
wasdas

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.CreateDataBase;
Was ist denn das eigentlich für ein Package-Name? Sieht aus wie ein Klassenname, und überhaupt..

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +public class ImportedGraph {
Doku fehlt.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +
extraneous newline

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +
überflüssig

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +	public ImportedGraph() {
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +	private GraphmlType type;
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +			System.out.print(e);
logger

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +	public void setType(GraphmlType type) {
warum ist das public?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +	public ImportedGraph() {
Kann es sein, dass diese Klasse auch ein Utility sein könnte? Was für State wird hier gekapselt?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExporterController.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.REST;
Oh, ein REST-Package für einen REST-Controller, geht doch! Aber allcaps ist kein gültiger Package-Name. Mach Dir bitte insgesamt nochmal Gedanken über eine sinnvolle Package-Struktur - vielleicht nach Zweck, oder nach Technologie, oder nach Use-Case?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExporterController.java
> +public class ExporterController {
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExporterController.java
> +				e1.printStackTrace();
logger

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExtractedGraph.java
> +public class ExtractedGraph {
Ich weiß, die Klasse ist glaube nicht von Dir, aber: Doku fehlt.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExtractedGraph.java
> +	final List<Map<Object, Object>> edges;
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExtractedGraph.java
> +		return builder.toString();
Hier lieber den StringBuilder zurückgeben, das serialisieren ist hier überflüssig, das macht dann der "Parent" mit.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ImporterController.java
> +public class ImporterController {
Doku fehlt

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ImporterController.java
> +			new BuiltGraph(imp.getGraphmlType());
Was gibt der im Response zurück?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ImporterController.java
> +				e1.printStackTrace();
logger

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/org/graphdrawing/graphml/xmlns/EdgeType.java
> +    }
Manuelle Ergänzungen sind in generierten Klassen nur wenig sinnstiftend. Die Faustregel ist, dass Generate jederzeit regenerierbar sein müssen. Wenn Du Ergänzungen haben willst, brauchst Du entweder einen Wrapper, oder eine Änderung des Generators.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +		cal = Calendar.getInstance();
Das möchte bitte nicht variabel sein, sondern ein festes Datum (oder mehrere) darstellen, anhand dessen dann die verschiedenen Fälle getestet werden. Die Idee ist, dass ein Test immer deterministisch ist, also leicht wiederholt werden kann, ohne dass sich in Abhängigkeit von äußeren Einflüssen das Ergebnis ändert. Dann fallen auch die ifs weiter unten in den @Tests weg, der Test muss stattdessen Fälle für alle Zweige dieses ifs bieten.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +		if(cal.get( Calendar.DAY_OF_WEEK ) != Calendar.SUNDAY)
siehe oben - alle Zweige brauchen eigene Tests

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +		while (zaehler != 0) {
ungewöhnlich, in einem Test. Könnte extra Dokumentation verdienen.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +		if(cal.get( Calendar.DAY_OF_WEEK ) != Calendar.SUNDAY)
siehe oben, alle Zweige bekommen eigene Tests.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +		while (zaehler != 0) {
siehe oben, Doku

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +				assertFalse(backup.keepBackup(obj));
siehe oben, Zweige mit eigenen Tests

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/BackupTest.java
> +		while (zaehler != 0) {
siehe oben, Doku

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/CompareXMLAWSTest.java
> +		new NeptuneAdapter().serialize(new FileWriter(resource.getFile()));
was ist die Quelle dieser Daten? Für einen Test muss die auch die Quelle fixiert werden ("Test Fixture"), deterministisch dies das

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/CompareXMLAWSTest.java
> +		AWSImporter awsimp = new AWSImporter();
Hierfür wäre es hilfreich, wenn wie oben angemerkt die Möglichkeit bestünde, beim Import ein Backup für die Wiederherstellung auszuwählen (a priori als Parameter). Möglicherweise bedeutet das für den Test, dass der Name des Backups auch beim Export von außen gesetzt werden können muss.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/CompareXMLAWSTest.java
> +		System.out.println(diffxml);
auskommentieren

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/CompareXMLRESTTest.java
> +	private static String filexml;
Felder gern an den Anfang der Klasse, wenn nichts anderes dagegenspricht.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/CompareXMLAWSTest.java
> +	private static String s3xml;
Felder gern an den Anfang der Klasse, wenn nichts anderes dagegenspricht.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/CompareXMLRESTTest.java
> +	void testXMLResttoFile() throws SAXException, IOException {
Wow, das ist ziemlich ungewöhnlich, BeforeAll für einen einzelnen Test-Fall zu nehmen. Bring das doch direkt im Testfall unter --- oder anders gefragt - welche weiteren Test-Cases könnte man basierend auf der Vorarbeit von BeforeAll noch machen, und wäre dann nicht wenigstens BeforeMethod besser? Wenn z.B. in sechs Monaten die Testsuite erweitert, was würde er dann erwarten, wie die Fixtures gebaut werden?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/EndtoEndTest.java
> +	private static GraphTraversalSource ge;
braucht zum besseren Verständnis bessere Namen oder ne Doku. oder beides.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/EndtoEndTest.java
> +		assertTrue(IteratorUtils.count(gs.V()) > 0);
IteratorUtils.count(gs.V()) kannst Du auch nur einmal berechnen lassen und dann zwei asserts auf dem Wert laufen lassen, wegen Performance?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/EndtoEndTest.java
> +	public static void setup() throws Exception {
Wo finde ich hier, welches Datenset für den Test verwendet wird?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/EndtoEndTest.java
> +		assertEquals(true,stvertlabel.isEmpty());
warum nicht direkt assertTrue?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/EndtoEndTest.java
> +	public void test() throws MalformedURLException {
aussagekräftigerer Name

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/FunctionTests.java
> + * @author LUNOACK
Durch den Einsatz von Mockito musst Du hier noch ein wenig ausführlicher dokumentieren - was mockst Du, und warum?

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/FunctionTests.java
> +	}
überflüssig, im Sinne der Codehygiene rausnehmen

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/NegativeFunctionTests.java
> + * Class to show that negative Parameters will not work
Auch hier wieder den Einsatz des Mocks erklären

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/NeptuneAdapter.java
> +public class NeptuneAdapter {
Doku fehlt :P

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/NeptuneAdapter.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.REST;
Erstmal: Warum ist der Package-Name nicht kleingeschrieben?
Dann: Der Neptun-Adapter gehört sicherlich nicht in das REST-Package? Aber weiter unten gibt's nochmal einen Kommentar zur Package-Struktur allgemein. Da müssen wir nochmal allgemein restrukturieren.

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/NeptuneAdapter.java
> +		final TinkerGraph graph = TinkerFactory.createGratefulDead();
Das wird in Praxis nicht funktionieren....

2020-03-25 22:57 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/NeptuneAdapter.java
> +	}
Diese beiden Methoden
* brauchen bessere Namen 
* und eine Doku, 
* und sollten wahrscheinlich nicht public sein

2020-04-06 15:34 UTC, ChristophSchmidt1203 requested changes
* Achte bitte darauf, dass Du alle Anmerkungen, die Du umsetzt auch tatsächlich schließt ("Resolve")
* Im Programmierstil gibt es derzeit noch ein paar kleine Unsauberkeiten. So ist mir z.B., aufgefallen, dass Du den Code gelegentlich "klitschst", besonders bei Argumente-Listen `a(param,para,par,pa,p)` -- Guck Dir mal STRG-SHIFT-F im Eclipse an :)
* Das Repo müssen wir bald mal in den OTTO-EC-Namensraum bringen.
* Für die REST-Schnittstelle hätte ich gern noch bessere Mapping-Namen, lass das mal im Teams besprechen, die vier Fälle, die es gibt.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSBackupEditor.java
> +		logger.info("Start Backup-Editor");
Genauere Ausgabe, sowas wie Starting Backup Housekeeping / Clean-Up, damit man nicht wissen muss, was mit Backup-Editor gemeint ist.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.Aws;
großes A im package-Namen ist nicht legal

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	 * Create temporary File
(Doku fehlt)

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +			tempfile =  File.createTempFile(uuid, ".xml");
Hier gibt's auch noch was: Wenn der Service NICHT nach einem Durchlauf runterfährt und komplett abgebaut wird, bleibt das Temp-File am Leben. Hier müsste also überlegt werden, ob nach der Verwendung das Tempfile durch die Anwendung gelöscht wird, z.B. mit deleteOnExit.. das kannst Du hier an der Stelle direkt aufrufen, dann brauchst Du es später nicht bedenken.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporterController.java
> +	 * This Method creates the Class AWSExporter.
Die Methode erstellt keine _Klasse_ :)

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +	public File createTempFile() {
Finde ich auch nicht gut benannt, das ist doch der eigentliche Einstieg, oder? Der erzeugt doch nicht nur ein Temp-File?

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporterController.java
> +			exporteraws.createTempFile();
Hier sieht man, warum die Methode etwas unglücklich benannt ist.. wenn ich das so lese würde ich nicht vermuten, was alles Schönes hinter dem Aufruf steckt.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	 * The Backup File which will be imported.
.. will be imported - von wo?

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +		if(backupfile.equals("")) {
defensiv programmieren, hier die Bedingung erweitern: null-Prüfung ergänzen

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	}
Das müssen wir unbedingt mal mit großen Datenmengen testen :)

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	 * After that it reads the File into a String and extracts the XML into the classes
Das auch: Unbedingt mal mit großen Datenmengen testen.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +		importer.stringtoXMLFile(data);
lieber den Getter nehmen, statt das Feld - weißt Du warum?

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	public BuiltGraph getGraph() {
Warum ist das public?

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporter.java
> +	public void setGraph(BuiltGraph graph) {
Warum ist das public?

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSImporterController.java
> +	@RequestMapping(value="/graphAWSIMP", method=RequestMethod.GET, produces=MediaType.APPLICATION_XML_VALUE)
braucht noch eine schönere URL - lass mal ein Benamungssystem für alle 4 Endpunkte entwickeln

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AmazonS3Configuration.java
> +	}
Schau bitte mal, welche dieser Beans _wirklich_ notwendig sind und nimm die anderen raus.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> + *
Doku

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +				.serializer(Serializers.GRAPHBINARY_V1D0);
Das muss auch noch extern konfigurierbar werden, mindestens der Contact Point und der Port. Wie beim S3..

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +		graph.V().drop().iterate();
Extra Log-Ausgabe für das DROP, mit hoher Sichtbarkeit.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/BuiltGraph.java
> +public class BuiltGraph {
Unten gibt's jetzt ein DROP

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ExtractedGraph.java
> +	 * These fields are the exported edges and nodes.
Dieser Kommentar ist für das Am-Stück-Lesen des Codes OK, aber wenn Du Dir in einer IDE Referenzen auf die Felder anguckst, taucht der Kommentar nur bei #nodes auf, nicht bei #edges -- lieber Aufteilen und jeder bekommt genau seine Doku.

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ExtractedGraph.java
> +		this.edges = edges==null?Collections.emptyList():edges;
Achtung, EmptyList ist stets leer, kann auch nicht beschrieben werden. Vielleicht lieber doch eine leere LinkedList jeweils verwenden?

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/CreateDataBase/ImportedGraph.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.Createdatabase;
Großes C im Package-Namen ersetzen

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExporterController.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.Rest;
Großes R im Packagenamen ersetzen

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ExporterController.java
> +			logger.error("Service ended with an Exception: {}",e);
Eigentlich hat hier nur der Aufruf ein Problem, nicht gleich der ganze Service :D

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/REST/ImporterController.java
> + * which gets Data from an REST-API and exctracts it into an Database.
typo extracts

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/NegativeFunctionTests.java
> +		});
ein schönes Pattern ist auch `try { shouldFail(1,2,3); } catch (ExpectedExceptionType e) { /* expected */ }`

2020-04-06 15:34 UTC, ChristophSchmidt1203 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/test/java/info/hiergiltdiestfu/aws/neptune/graphml/NegativeFunctionTests.java
> +		});
(nur als Info)

2020-04-13 08:57 UTC, Lucas-SpiridonasNoack4321 commented on info.hiergiltdiestfu.aws.neptune.graphml/src/main/java/info/hiergiltdiestfu/aws/neptune/graphml/AWS/AWSExporter.java
> +package info.hiergiltdiestfu.aws.neptune.graphml.Aws;
alles kleingeschrieben

2020-04-14 07:32 UTC, ChristophSchmidt1203 approved these changes

2020-04-14 07:32 UTC, merged